name: sagile_mobile
description: A new Flutter project.

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  http: ^0.13.5
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  formz: ^0.4.0
  user_repository:
    path: packages/user_repository
  project_repository:
    path: packages/project_repository
  table_calendar: ^3.0.9
  salomon_bottom_bar: ^3.3.2
  intl: ^0.18.1
  fl_chart: ^1.1.1
flutter:
  uses-material-design: true